name: spring
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - libcxx
  - libffi
  - ncurses
  - openssl
  - readline
  - sqlite
  - tk
  - tzdata
  - xz
  - zlib
  - pip:
      - pygame==2.6.1
